### PR TITLE
Repo restructure to deal with maven

### PR DESCRIPTION
**Pull request by otron**
Part of maven's release plugin breaks when there is no valid pom-file exactly named `pom.xml` in the working directory root, so the pom-v1 and pom-v0 approach turned out to be useless.

### CODE REVIEW

**Review by phgroe — APPROVED** [review]
All good! I just pushed a small update with an increased version number in package.json

**Comment by gi-wg2** [comment]
Any reason for that extra version tag? And did you remove the `wgtwo` folder?

I would assume it would be something like either
```
https://github.com/working-group-two/wgtwoapis/wgtwo/v0/sms/some.proto
```

and not

```
https://github.com/working-group-two/wgtwoapis/v0/sms/v0/some.proto
```

This is the Google API for reference:
https://github.com/googleapis/googleapis

This is where Google keeps their Java code in another repo: https://github.com/googleapis/google-api-java-client-services

We could go for that as well...

**Comment by gi-wg2** [comment]
You could just move the v0 and v1 pom to each their folder as well? And keep things as it?

**Comment by otron** [comment]
> You could just move the v0 and v1 pom to each their folder as well? And keep things as it?

Yes.

**Pull request merged**
